-- AlterTable
ALTER TABLE "ProviderModel" ADD COLUMN "costCachedInputPer1M" DOUBLE PRECISION;
ALTER TABLE "ProviderModel" ADD COLUMN "costCacheWritePer1M" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "RequestLog" ADD COLUMN "savingsInputFresh" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RequestLog" ADD COLUMN "savingsCacheRead" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RequestLog" ADD COLUMN "savingsCacheCreation" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RequestLog" ADD COLUMN "savingsOutput" DOUBLE PRECISION NOT NULL DEFAULT 0;
